using System;
using Xunit;

namespace CheetahRacingAppTests
{
    public class UnitTest1
    {

        [Fact]
        public void Test1()
        {
            // Unable to create any unit tests for the project since all of the Controllers' code was generated by visual studio, no need to re-test it.

        }
    }
}
